// Generated by `bettervibes init` / `bettervibes inventory-sync` from BV's
// bundled source. Do not edit — `bettervibes inventory-sync` overwrites this
// file unconditionally.
//
// Run from the project root:
//   npx tsx bv_orchestration/scripts/inventory.ts
//
// Regenerates `bv_orchestration/inventory.csv` from the T-NN files under
// `bv_orchestration/tasks/{new,stage,done}/` and the WR-NN files under
// `bv_orchestration/logs/worker-reports/`. Incremental: rows whose derived
// values are unchanged are emitted bytewise-identical to preserve git blame.

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';

type Frontmatter = Record<string, string | string[]>;

interface Row {
  task_id: string;
  task_name: string;
  prd_source: string;
  is_done: string;
  date_added: string;
  date_finished: string;
}

interface WorkerReport {
  filename: string;
  date: string;
}

const HEADER = 'task_id,task_name,prd_source,is_done,date_added,date_finished';
const COLUMNS: Array<keyof Row> = [
  'task_id',
  'task_name',
  'prd_source',
  'is_done',
  'date_added',
  'date_finished',
];

const TASK_FILENAME = /^T-(\d+)-(\d{4}-\d{2}-\d{2})\.md$/;
const WR_FILENAME = /^(WR-\d+)-.+-(\d{4}-\d{2}-\d{2})\.md$/;
const WR_ID_PREFIX = /^(WR-\d+)/;
const TASK_H1 = /^#\s+Task:\s*(.+?)\s*$/m;
const FRONTMATTER_KEY = /^([A-Za-z0-9_\-]+)\s*:\s*(.*)$/;
const BLOCK_ARRAY_ITEM = /^\s+-\s*(.*)$/;

async function readdirSafe(dir: string): Promise<string[]> {
  try {
    return await readdir(dir);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw err;
  }
}

function stripQuotes(s: string): string {
  if (s.length >= 2) {
    const first = s[0];
    const last = s[s.length - 1];
    if ((first === '"' || first === "'") && first === last) {
      return s.slice(1, -1);
    }
  }
  return s;
}

function parseFrontmatter(raw: string): { data: Frontmatter; body: string } {
  const opens = raw.startsWith('---\n')
    ? 4
    : raw.startsWith('---\r\n')
    ? 5
    : 0;
  if (opens === 0) return { data: {}, body: raw };

  const rest = raw.slice(opens);
  const closeMatch = rest.match(/\n---(?:\r?\n|$)/);
  if (!closeMatch || closeMatch.index === undefined) {
    return { data: {}, body: raw };
  }
  const yamlText = rest.slice(0, closeMatch.index);
  const body = rest.slice(closeMatch.index + closeMatch[0].length);

  const data: Frontmatter = {};
  const lines = yamlText.split(/\r?\n/);
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === '' || line.trimStart().startsWith('#')) {
      i++;
      continue;
    }
    const m = line.match(FRONTMATTER_KEY);
    if (!m) {
      i++;
      continue;
    }
    const key = m[1];
    const valuePart = m[2];

    if (valuePart === '') {
      const items: string[] = [];
      let j = i + 1;
      while (j < lines.length) {
        const itemMatch = lines[j].match(BLOCK_ARRAY_ITEM);
        if (!itemMatch) break;
        items.push(stripQuotes(itemMatch[1].trim()));
        j++;
      }
      data[key] = items;
      i = j;
      continue;
    }

    if (valuePart.startsWith('[') && valuePart.endsWith(']')) {
      const inner = valuePart.slice(1, -1).trim();
      if (inner === '') {
        data[key] = [];
      } else {
        data[key] = inner
          .split(',')
          .map((s) => stripQuotes(s.trim()))
          .filter((s) => s.length > 0);
      }
      i++;
      continue;
    }

    data[key] = stripQuotes(valuePart.trim());
    i++;
  }

  return { data, body };
}

async function buildWrIndex(reportsDir: string): Promise<Map<string, WorkerReport>> {
  const index = new Map<string, WorkerReport>();
  const entries = await readdirSafe(reportsDir);
  const sorted = [...entries].sort();
  for (const filename of sorted) {
    const m = filename.match(WR_FILENAME);
    if (!m) continue;
    index.set(m[1], { filename, date: m[2] });
  }
  return index;
}

function frontmatterString(data: Frontmatter, key: string): string {
  const v = data[key];
  return typeof v === 'string' ? v : '';
}

function frontmatterArray(data: Frontmatter, key: string): string[] {
  const v = data[key];
  return Array.isArray(v) ? v : [];
}

function normalizePrdSource(value: string): string {
  if (value === '') return '';
  return basename(value).replace(/\.md$/, '');
}

function deriveTaskName(body: string): string {
  const m = body.match(TASK_H1);
  return m ? m[1] : '';
}

async function deriveRow(
  filename: string,
  taskDir: string,
  reportsIndex: Map<string, WorkerReport>,
  stderr: NodeJS.WritableStream
): Promise<Row | null> {
  const m = filename.match(TASK_FILENAME);
  if (!m) return null;
  const task_id = `T-${m[1]}`;
  const date_added = m[2];

  const raw = await readFile(join(taskDir, filename), 'utf8');
  const { data, body } = parseFrontmatter(raw);

  const task_name = deriveTaskName(body);
  if (task_name === '') {
    stderr.write(`warning: ${task_id}: missing \`# Task: <name>\` H1 in ${filename}\n`);
  }

  const prd_source = normalizePrdSource(frontmatterString(data, 'prd-source'));
  const status = frontmatterString(data, 'status');
  const is_done = status === 'done' ? 'true' : 'false';

  let date_finished = '';
  if (is_done === 'true') {
    const refs = frontmatterArray(data, 'worker-reports');
    const dates: string[] = [];
    for (const ref of refs) {
      const idMatch = ref.match(WR_ID_PREFIX);
      if (!idMatch) {
        stderr.write(`warning: ${task_id}: unparseable worker-reports entry: ${ref}\n`);
        continue;
      }
      const wrId = idMatch[1];
      const found = reportsIndex.get(wrId);
      if (!found) {
        stderr.write(`warning: ${task_id}: worker report ${wrId} not found in logs/worker-reports/\n`);
        continue;
      }
      dates.push(found.date);
    }
    if (dates.length > 0) {
      dates.sort();
      date_finished = dates[dates.length - 1];
    }
  }

  return { task_id, task_name, prd_source, is_done, date_added, date_finished };
}

function csvEscape(cell: string): string {
  if (cell === '') return '';
  if (/[",\r\n]/.test(cell)) {
    return `"${cell.replace(/"/g, '""')}"`;
  }
  return cell;
}

function serializeRow(row: Row): string {
  return COLUMNS.map((c) => csvEscape(row[c])).join(',');
}

function parseCsvLine(line: string): string[] {
  const cells: string[] = [];
  let cur = '';
  let inQuotes = false;
  let i = 0;
  while (i < line.length) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i += 2;
          continue;
        }
        inQuotes = false;
        i++;
        continue;
      }
      cur += ch;
      i++;
      continue;
    }
    if (ch === '"') {
      inQuotes = true;
      i++;
      continue;
    }
    if (ch === ',') {
      cells.push(cur);
      cur = '';
      i++;
      continue;
    }
    cur += ch;
    i++;
  }
  cells.push(cur);
  return cells;
}

async function readExistingCsv(csvPath: string): Promise<Map<string, string>> {
  const map = new Map<string, string>();
  let raw: string;
  try {
    raw = await readFile(csvPath, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return map;
    throw err;
  }
  const lines = raw.replace(/\r\n/g, '\n').split('\n');
  if (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  if (lines.length > 0 && lines[0] === HEADER) lines.shift();
  for (const line of lines) {
    if (line === '') continue;
    const cells = parseCsvLine(line);
    if (cells.length === 0 || cells[0] === '') continue;
    map.set(cells[0], line);
  }
  return map;
}

async function scanTasks(
  bvDir: string,
  reportsIndex: Map<string, WorkerReport>,
  stderr: NodeJS.WritableStream
): Promise<Row[]> {
  const buckets = ['done', 'stage', 'new'] as const;
  const byId = new Map<string, { row: Row; bucket: string }>();

  for (const bucket of buckets) {
    const dir = join(bvDir, 'tasks', bucket);
    const entries = await readdirSafe(dir);
    for (const entry of entries) {
      if (!TASK_FILENAME.test(entry)) continue;
      const row = await deriveRow(entry, dir, reportsIndex, stderr);
      if (!row) continue;
      const existing = byId.get(row.task_id);
      if (existing) {
        stderr.write(
          `warning: ${row.task_id} appears in both tasks/${existing.bucket}/ and tasks/${bucket}/; keeping ${existing.bucket}/\n`
        );
        continue;
      }
      byId.set(row.task_id, { row, bucket });
    }
  }

  return [...byId.values()]
    .map((v) => v.row)
    .sort((a, b) => (a.task_id < b.task_id ? -1 : a.task_id > b.task_id ? 1 : 0));
}

async function generateInventory(
  root: string,
  stderr: NodeJS.WritableStream
): Promise<void> {
  const bvDir = join(root, 'bv_orchestration');
  const reportsDir = join(bvDir, 'logs', 'worker-reports');
  const csvPath = join(bvDir, 'inventory.csv');

  const reportsIndex = await buildWrIndex(reportsDir);
  const rows = await scanTasks(bvDir, reportsIndex, stderr);
  const existing = await readExistingCsv(csvPath);

  const newIds = new Set(rows.map((r) => r.task_id));
  for (const id of existing.keys()) {
    if (!newIds.has(id)) {
      stderr.write(
        `warning: ${id} present in existing inventory.csv but not on disk; dropping row\n`
      );
    }
  }

  const lines: string[] = [HEADER];
  for (const row of rows) {
    const serialized = serializeRow(row);
    const prior = existing.get(row.task_id);
    lines.push(prior !== undefined && prior === serialized ? prior : serialized);
  }

  await writeFile(csvPath, lines.join('\n') + '\n', 'utf8');
}

async function main(): Promise<number> {
  try {
    await generateInventory(process.cwd(), process.stderr);
    return 0;
  } catch (err) {
    process.stderr.write(`fatal: ${(err as Error).message}\n`);
    return 1;
  }
}

main().then(
  (code) => process.exit(code),
  (err) => {
    process.stderr.write(`${(err as Error).stack ?? (err as Error).message}\n`);
    process.exit(1);
  }
);
